# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/sagnac/Quantum/lab/focus/ui/focus.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(838, 654)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.splitter_4 = QtGui.QSplitter(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_4.sizePolicy().hasHeightForWidth())
        self.splitter_4.setSizePolicy(sizePolicy)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName(_fromUtf8("splitter_4"))
        self.label_21 = QtGui.QLabel(self.splitter_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(self.splitter_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.layoutWidget = QtGui.QWidget(self.splitter_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_23 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_3.addWidget(self.label_23, 0, 0, 1, 1)
        self.lblA0 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lblA0.setFont(font)
        self.lblA0.setAlignment(QtCore.Qt.AlignCenter)
        self.lblA0.setObjectName(_fromUtf8("lblA0"))
        self.gridLayout_3.addWidget(self.lblA0, 0, 1, 1, 1)
        self.label_26 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_3.addWidget(self.label_26, 1, 0, 1, 1)
        self.lblA1 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lblA1.setFont(font)
        self.lblA1.setAlignment(QtCore.Qt.AlignCenter)
        self.lblA1.setObjectName(_fromUtf8("lblA1"))
        self.gridLayout_3.addWidget(self.lblA1, 1, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_3.addWidget(self.label_25, 2, 0, 1, 1)
        self.lblA2 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lblA2.setFont(font)
        self.lblA2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblA2.setObjectName(_fromUtf8("lblA2"))
        self.gridLayout_3.addWidget(self.lblA2, 2, 1, 1, 1)
        self.label_29 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_3.addWidget(self.label_29, 3, 0, 1, 1)
        self.lblA3 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lblA3.setFont(font)
        self.lblA3.setAlignment(QtCore.Qt.AlignCenter)
        self.lblA3.setObjectName(_fromUtf8("lblA3"))
        self.gridLayout_3.addWidget(self.lblA3, 3, 1, 1, 1)
        self.layoutWidget1 = QtGui.QWidget(self.splitter_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.layoutWidget1.setFont(font)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_31 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_2.addWidget(self.label_31)
        self.lblWaist = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lblWaist.setFont(font)
        self.lblWaist.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblWaist.setObjectName(_fromUtf8("lblWaist"))
        self.horizontalLayout_2.addWidget(self.lblWaist)
        self.label_33 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_33.setFont(font)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_2.addWidget(self.label_33)
        self.gridLayout_2.addWidget(self.splitter_4, 0, 2, 2, 1)
        self.splitter_2 = QtGui.QSplitter(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.layoutWidget2 = QtGui.QWidget(self.splitter_2)
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.formLayout = QtGui.QFormLayout(self.layoutWidget2)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.comboBox = QtGui.QComboBox(self.layoutWidget2)
        self.comboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.comboBox)
        self.label_15 = QtGui.QLabel(self.layoutWidget2)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_15)
        self.lineEdit_7 = QtGui.QLineEdit(self.layoutWidget2)
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_7)
        self.label_14 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.SpanningRole, self.label_14)
        self.layoutWidget3 = QtGui.QWidget(self.splitter_2)
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.t = QtGui.QLineEdit(self.layoutWidget3)
        self.t.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.t.setObjectName(_fromUtf8("t"))
        self.gridLayout.addWidget(self.t, 1, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget3)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 2, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget3)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget3)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget3)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.txtStep = QtGui.QLineEdit(self.layoutWidget3)
        self.txtStep.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtStep.setObjectName(_fromUtf8("txtStep"))
        self.gridLayout.addWidget(self.txtStep, 2, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget3)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 1, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget3)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.txtMin = QtGui.QLineEdit(self.layoutWidget3)
        self.txtMin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtMin.setObjectName(_fromUtf8("txtMin"))
        self.gridLayout.addWidget(self.txtMin, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.splitter_2, 1, 0, 1, 1)
        self.splitter_5 = QtGui.QSplitter(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_5.sizePolicy().hasHeightForWidth())
        self.splitter_5.setSizePolicy(sizePolicy)
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName(_fromUtf8("splitter_5"))
        self.btnStart = QtGui.QPushButton(self.splitter_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnStart.setFont(font)
        self.btnStart.setObjectName(_fromUtf8("btnStart"))
        self.splitter = QtGui.QSplitter(self.splitter_5)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.label = QtGui.QLabel(self.splitter)
        self.label.setObjectName(_fromUtf8("label"))
        self.txtAverage = QtGui.QLineEdit(self.splitter)
        self.txtAverage.setAlignment(QtCore.Qt.AlignCenter)
        self.txtAverage.setObjectName(_fromUtf8("txtAverage"))
        self.gridLayout_2.addWidget(self.splitter_5, 0, 0, 1, 1)
        self.ltErf = QtGui.QHBoxLayout()
        self.ltErf.setObjectName(_fromUtf8("ltErf"))
        self.gridLayout_2.addLayout(self.ltErf, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.ltOscilloscope = QtGui.QHBoxLayout()
        self.ltOscilloscope.setObjectName(_fromUtf8("ltOscilloscope"))
        self.gridLayout_4.addLayout(self.ltOscilloscope, 0, 1, 1, 1)
        self.splitter_6 = QtGui.QSplitter(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_6.sizePolicy().hasHeightForWidth())
        self.splitter_6.setSizePolicy(sizePolicy)
        self.splitter_6.setOrientation(QtCore.Qt.Vertical)
        self.splitter_6.setObjectName(_fromUtf8("splitter_6"))
        self.btnOscilloscope = QtGui.QPushButton(self.splitter_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOscilloscope.sizePolicy().hasHeightForWidth())
        self.btnOscilloscope.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnOscilloscope.setFont(font)
        self.btnOscilloscope.setObjectName(_fromUtf8("btnOscilloscope"))
        self.splitter_3 = QtGui.QSplitter(self.splitter_6)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.label_18 = QtGui.QLabel(self.splitter_3)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.txtPause = QtGui.QLineEdit(self.splitter_3)
        self.txtPause.setEnabled(True)
        self.txtPause.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtPause.setObjectName(_fromUtf8("txtPause"))
        self.label_17 = QtGui.QLabel(self.splitter_3)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.layoutWidget4 = QtGui.QWidget(self.splitter_6)
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lblPower = QtGui.QLabel(self.layoutWidget4)
        self.lblPower.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPower.setObjectName(_fromUtf8("lblPower"))
        self.horizontalLayout.addWidget(self.lblPower)
        self.label_20 = QtGui.QLabel(self.layoutWidget4)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout.addWidget(self.label_20)
        self.gridLayout_4.addWidget(self.splitter_6, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.splitter.raise_()
        self.splitter_2.raise_()
        self.splitter_3.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.btnStart.raise_()
        self.btnOscilloscope.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.layoutWidget.raise_()
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_21.setText(_translate("MainWindow", "Fit results", None))
        self.label_22.setText(_translate("MainWindow", "f = a[0]*erfc(a[1]*(P-a[2]))+a[3]", None))
        self.label_23.setText(_translate("MainWindow", "a[0]", None))
        self.lblA0.setText(_translate("MainWindow", "0", None))
        self.label_26.setText(_translate("MainWindow", "a[1]", None))
        self.lblA1.setText(_translate("MainWindow", "0", None))
        self.label_25.setText(_translate("MainWindow", "a[2]", None))
        self.lblA2.setText(_translate("MainWindow", "0", None))
        self.label_29.setText(_translate("MainWindow", "a[3]", None))
        self.lblA3.setText(_translate("MainWindow", "0", None))
        self.label_31.setText(_translate("MainWindow", "Waist", None))
        self.lblWaist.setText(_translate("MainWindow", "0", None))
        self.label_33.setText(_translate("MainWindow", "um", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "thorlabs", None))
        self.label_15.setText(_translate("MainWindow", "SN", None))
        self.label_14.setText(_translate("MainWindow", "Linear stage", None))
        self.t.setText(_translate("MainWindow", "0.5", None))
        self.label_7.setText(_translate("MainWindow", "mm", None))
        self.label_5.setText(_translate("MainWindow", "mm", None))
        self.label_2.setText(_translate("MainWindow", "Min", None))
        self.label_3.setText(_translate("MainWindow", "Max", None))
        self.txtStep.setText(_translate("MainWindow", "0.02", None))
        self.label_6.setText(_translate("MainWindow", "mm", None))
        self.label_4.setText(_translate("MainWindow", "Step", None))
        self.txtMin.setText(_translate("MainWindow", "0", None))
        self.btnStart.setText(_translate("MainWindow", "Start", None))
        self.label.setText(_translate("MainWindow", "Average", None))
        self.txtAverage.setText(_translate("MainWindow", "10", None))
        self.btnOscilloscope.setText(_translate("MainWindow", "Oscilloscope", None))
        self.label_18.setText(_translate("MainWindow", "ms", None))
        self.txtPause.setText(_translate("MainWindow", "10", None))
        self.label_17.setText(_translate("MainWindow", "Pause", None))
        self.lblPower.setText(_translate("MainWindow", "0", None))
        self.label_20.setText(_translate("MainWindow", "mW", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

